name: presentation demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: access to the repo
        uses: actions/checkout@v3
      - name: install dart
        uses: dart-lang/setup-dart@v1
        
